consul:
  image: autopilotpattern/consul:1.0.0r43
  command: >
    /usr/local/bin/containerpilot
  environment:
   - CONSUL_DEV=1
   - CONSUL=localhost
  restart: always
  mem_limit: 512m
  ports:
    - 9090:9090
    - 8500:8500

webconsole-instances:
  build: ./
  restart: always
  mem_limit: 1g
  env_file:
    - _env
    - _env_consul
  links:
    - consul:consul
  ports:
    - 80:80
    - 443:443
